development:
  adapter: postgresql
  database: gate_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: gate_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: gate_production
  pool: 5
  timeout: 5000
